//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusEd
{
    public partial class View
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.SiteMapPath SiteMapPath1;

        protected global::System.Web.UI.WebControls.Menu Menu1;

        protected global::System.Web.UI.WebControls.SiteMapDataSource SiteMapDataSource1;

        protected global::System.Web.UI.WebControls.GridView gvFeedback;
    }
}
